accounts:
  - name: alice
    coins: ["1000token", "100000000stake"]
  - name: bob
    coins: ["500token"]
validator:
  name: alice
  staked: "100000000stake"
servers:
  dev-ui-address: "localhost:12345"
genesis:
  chain_id: "umee-test"
