# This workflow helps with creating releases.
# This job will only be triggered when a tag (vX.X.x) is pushed
name: Umeed Docker Release
on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+" # Push only official release version tags e.g. v2.0.5

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  umeed-docker:
    name: umee Docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          # github.repository == <account>/<repo>
          images: ghcr.io/${{ github.repository_owner }}/umeed
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern=latest-{{major}}.{{minor}}
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Print tags and labels
        run: |
          echo image: ${{ env.REGISTRY }}/${{ github.repository }}
          echo tags "${{ steps.meta.outputs.tags }}"
          echo labels "${{ steps.meta.outputs.labels }}"

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate swagger docs 
        run: |
          make proto-swagger-gen
          make proto-update-swagger-docs

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./contrib/images/umeed.dockerfile
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64  # requires qemu action
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
